---
title: "milestone4"
author: "Janna Ramadan"
date: "10/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(rtweet)
library(tidytext)
library(dplyr)
library(ggplot2)
library(readr)
library(gganimate)
library(shiny)
```


```{r, hate-crime-data-set-up}
# load datasets


fbi2018 <- read_excel("rawdata/fbi2018.xls") %>%
  slice(4: 49) %>%
  select(1, 4) 
  # names(Table 1) <- "Bias Motivation" %>%
  # names(...4) <- "Number of Victims"

fbi2017 <- read_excel("rawdata/fbi2017.xls")%>%
  slice(3: 49) %>%
  select(1, 4)

fbi2016 <- read_excel("rawdata/fbi2016.xls")%>%
  slice(3: 49) %>%
  select(1, 4)

fbi2015 <- read_excel("rawdata/fbi2015.xls") %>%
  slice(3: 49) %>%
  select(1, 4)

fbi2014 <- read_excel("rawdata/fbi2014.xls") %>%
  slice(3: 49) %>%
  select(1, 4)

fbi2013 <- read_excel("rawdata/fbi2013.xls") %>%
  slice(3: 49) %>%
  select(1, 4)

fbi2012 <- read_excel("rawdata/fbi2012.xls") %>%
  slice(3: 49) %>%
  select(1, 4)

```

```{r, hate-crime-making-one-data-set }
fbi78 <- full_join(fbi2018, fbi2017) %>%
  #  as.data.frame(apply(as.numeric)) %>%
  rename(bias_motivation = "Table 1", count = "...4") %>%
  filter(bias_motivation == "Anti-Islamic (Muslim)" | bias_motivation == "Anti-Arab") 

fbi56 <- full_join(fbi2015, fbi2016) %>%
  rename(bias_motivation = "Table 1", count = "...4") %>%
  filter(bias_motivation == "Anti-Islamic (Muslim)" | bias_motivation == "Anti-Arab") 

fbi34 <- full_join(fbi2013, fbi2014) %>%
  rename(bias_motivation = "Table 1", count = "...4") %>%
  filter(bias_motivation == "Anti-Islamic (Muslim)" | bias_motivation == "Anti-Arab") 

fbi2 <- fbi2012 %>%
  rename(bias_motivation = "Table 1", count = "...4") %>%
  filter(bias_motivation == "Anti-Islamic" | bias_motivation == "Anti-Arab")

  fbi2[1,1] <- "Anti-Islamic (Muslim)"

fbi5_8 <- full_join(fbi56, fbi78)
fbi2_4 <- full_join(fbi2, fbi34)


fbi12_18 <- full_join(fbi2_4, fbi5_8)

  fbi12_18$year <- c("2012", "2013", "2014", "2015", "2015", "2016", "2016", "2018", "2018", "2017", "2017")

  fbicompiled <- fbi12_18 %>%
    mutate("count" = as.numeric(count)) %>%
    arrange(desc(count))
  #find away to set cols earlier while merging
    
write_csv(fbicompiled, "fbicompiled.csv")
    
  
```

```{r, hate-crime-graph}

      ggplot(data = fbicompiled, mapping = aes(x = year, y = count, color = bias_motivation)) +
        geom_point(size = 2) +
        theme_bw() +
        labs(title = "2012-2018 Count of Hate Crimes\n Motivated By Anti-Muslim or \nAnti-Arab Sentiment",
             subtitle = "Counts victims of hate crimes \nwithin the United States",
             x = "Year",
             y = "Victim Count",
             caption = "Source: FBI Hate Crimes") +
        scale_color_manual(name = "Hate Crime Motivation",
                           labels = c("Anti-Arab \nSentiment", "Anti-Muslim \nSentiment"),
                           values = c("olivedrab3", "lightskyblue2")) +
        theme(axis.text.x = element_text(size = 5, angle = 45),
              text = element_text(family = "Palatino"))

```

```{r, google-trend-news-data}
library(lubridate)
library(janitor)
library(ggplot2)
library(gganimate)


#data download and clean up
newstrends08_20 <- read_csv("rawdata/googletrends.csv",
  col_types = list(
  Month = col_character(),
  Year = col_double(),
  Month_1 = col_double(),
 `Month (Name)` = col_character(),
 Muslim = col_double(),
   Terrorism = col_double())) %>%  
  clean_names() %>%
  mutate(month = ymd(month, truncated = 1)) 

newstrends08_20 <- newstrends08_20 %>%
  pivot_longer(cols = c(muslim, terrorism), 
               names_to = "key_word") %>%
  rename(date = month) %>%
  rename(month = month_1)

# makes csv of cleaned data
write_csv(newstrends08_20, "newstrends0820.csv")

#graph of trends
ggplot(data = newstrends08_20, mapping = aes(x = date, 
                                              y = value, 
                                              color = key_word)) +
  geom_line() +
 transition_reveal(date) +
  scale_x_date(date_labels = "%b/%Y", date_breaks = "year") +
  theme(axis.text.x = element_text(size = 5, angle = 90),
              text = element_text(family = "Palatino")) +
  scale_color_manual(values = c("olivedrab3", "brown2"), labels = c("Muslim", "Terorrism"), name = "Key Word Search Term") +
  labs(title = "Level of Search Interest in the Topic 'Muslim' and Search Term 'Terrorist'",
       subtitle = "Values Based on Google News Search Trends Between 2008 and 2020", 
       x = "Date", 
       y = "Relative Interest (with respect to peak search frequency)", 
       caption = "Source: Google News Trends")

# is this an accurate measure of the news? if it's news searches
# how do you list multiple graphs in shiny
# twitter???

```


```{r}

#ggplot(data = newstrends08_20, mapping = aes(x = months.Date())) +
  #geom_histogram()

#, 
 #                           cols(
 # Month = col_character(),
 # Year = col_double(),
 # Month_1 = col_double(),
 # `Month (Name)` = col_character(),
 # Muslim = col_double(),
 # Terrorism = col_double()
# ))
```


```{r}

# newstrend breakdown by year data - unnecessary for now 
# newstrendbyyear <- newstrends08_20 %>%
#   group_by(year, key_word) %>%
#   summarize(total_hits = sum(value))
# 
# muslimtrendbyyear <- newstrendbyyear %>%
#   filter(key_word == "Muslim")
# 
# terrorismtrendbyyear <- newstrendbyyear %>%
#   filter(key_word == "Terrorism")
# 
# write_csv(newstrends08_20, "newstrends.csv")
# write_csv(muslimtrendbyyear, "muslimtrendbyyear.csv")
# write_csv(terrorismtrendbyyear, "terrorismtrendbyyear.csv")
# 
# #terrorism search trend graph
# ggplot(data = terrorismtrendbyyear , mapping = aes(x = Year, y = total_hits, color = key_word)) +
#   geom_line() +
#   theme(axis.text.x = element_text(size = 5, angle = 90),
#               text = element_text(family = "Palatino"))
# 
# #Muslim search trend graph
# ggplot(data = muslimtrendbyyear , mapping = aes(x = Year, y = total_hits, color = key_word)) +
#   geom_line() +
#   theme(axis.text.x = element_text(size = 5, angle = 90),
#               text = element_text(family = "Palatino"))
# 
# #Compared data grapg
# ggplot(data = newstrendbyyear , mapping = aes(x = Year, y = total_hits, color = key_word)) +
#   geom_line() +
#   theme(axis.text.x = element_text(size = 5, angle = 90),
#               text = element_text(family = "Palatino"))

#attempt at long term trends
```



```{r, twitter attempt content}
appname <- "muslimopinion"
  
key <- "nTjL6wXzSH6m0A0NWaYOqJ7qH76Y8q01Jaa1YNujCdjAjk4poQ"

secretkey <- "nTjL6wXzSH6m0A0NWaYOqJ7qH76Y8q01Jaa1YNujCdjAjk4poQ"

muslim_extremist_search_string <- c("muslim extremist", "muslim terrorist", "muslim radical")

muslimradicals_tweets <- search_tweets(type = "recent", 
                                       q = "muslim terrorist",
                               n = 100, 
                               include_rts = FALSE,
                               "lang:en",
                               geocode = lookup_coords("usa"))  %>%
  select("created_at", "text", "hashtags")

# https://en.wikipedia.org/wiki/Geographic_center_of_the_contiguous_United_States
# shows that Lebanon, kensas is the midpoint of the continuous US.

#twitter_token <- create_token(
 # app = appname,
 # consumer_key = key,
 # consumer_secret = secretkey)
```

```{r}
# shiny notes
    #fluidPage(
    # titlePanel("Model Title"),
    # sidebarLayout(
    # sidebarPanel(
    #  textInput("name", "What's your name?"),  
    #  textOutput("greeting"),
    # sliderInput("year", label="When were you born?",   
    #             min = 1960, max = 2020, value = 2000),  
    # textOutput("AgeCalc"),
    # selectInput(
    #    "plot_type",
    #    "Plot Type",
    #    c("Option A" = "a", "Option B" = "b")
    
    #   )),
    # mainPanel())
    # )),
```

```{r}
# section questions
# - how do i add columns bc I found more data from the fbi on hate crime stats : 
#   https://www.pewresearch.org/fact-tank/2017/11/15/assaults-against-muslims-in-u-s-surpass-2001-level/
#   
# what do i do about twitter - how do i measure it
# 
# how do I include multipe putput graphs - done!
# how to save the gif to take less space loading - needs outfile, animate, etc. 
# less favorable to animation to diff countries, unless u save gifs at once and load
# future q - how you load 
  
```

